# Choisir une image de base
FROM mcp/postgres

# Définir le répertoire de travail
WORKDIR ./

# Copier les fichiers nécessaires
COPY <source> <destination>

# Installer les dépendances
RUN <commande>

# Exposer les ports nécessaires
EXPOSE 5000:5000

# Définir la commande de démarrage
CMD ["<commande>"]